find . -name .DS_Store -type f -delete
find . -name .project -type f -delete
find . -name .classpath -type f -delete
rm -rf `find . -name .settings -type d`
rm -rf `find . -name target -type d`

zip -r code.zip code